#!/bin/bash

echo "🚂 Railway Quick Start Helper"
echo "================================"
echo ""
echo "✅ Your bot is ready for Railway!"
echo ""
echo "📋 Next Steps:"
echo "1. Go to: https://railway.app"
echo "2. Click 'New Project'"
echo "3. Click 'Deploy from GitHub'"
echo "4. Select this repository"
echo "5. Add these environment variables:"
echo "   - TELEGRAM_BOT_TOKEN (your bot token)"
echo "   - CHANNEL_ID (your channel ID)"
echo "   - GEMINI_API_KEY (your API key)"
echo "   - SCHEDULE_ENABLED=true"
echo "   - POSTING_INTERVAL_HOURS=4"
echo ""
echo "6. Click Deploy!"
echo ""
echo "🎉 Bot will run 24/7 automatically!"
echo ""
echo "📖 Having issues? Read RAILWAY_FIX.md"
